### ISSUE TITLE
Need a new release with updated bindbc-sdl dependency

### ISSUE THREAD

**Issue by mdparker** [BindBC/bindbc-imgui#1]
The bindbc-sdl dependency in master is 1.1.2, but the last bindbc-imgui release (0.7.0) depends on 0.21.4. This is causing a conflict in inochi-creator. See https://forum.dlang.org/post/vwesvgnuafhhvncxxfyb@forum.dlang.org.

Please tag a new bindbc-imgui release so that the updated dependency is out there.

**Comment by ichordev** [comment]
Oops I forgot to post my reply to this the other day.
Basically, from what I can see the user who posted that on the forums made an error. First of all, when building Inochi-Creator you’re meant to manually download the `~master` branch of all of its dependencies from the appropriate `Inochi2D/` repositories and use `dub add-local` on them. Inochi-Creator is also not a library, so the fact that they added it as a dependency means that they weren’t using the package correctly. Lastly, I cannot guarantee that the most recent commit is a stable version, or in any way API-compatible with 0.7.0.
