### ISSUE TITLE
Cmake 3.31.2 fails when building 2D imgui 

### ISSUE THREAD

**Issue by Hakazaba** [BindBC/bindbc-imgui#4]
[Log.txt](https://github.com/user-attachments/files/18060798/Log.txt)

I'm having difficulty setting up Inochi to build, Could i please have some guidance to get this to work? 
A build log is attached.

**Comment by ichordev** [comment]
Wrong repository. From reading the log, you’re actually using this: https://github.com/Inochi2D/i2d-imgui

This repository currently hosts an older mirror of i2d-imgui (not made by me so I can’t provide support for it, it’s just here for dub package name backwards-compatibility reasons), but I’m rewriting these bindings from scratch—in fact the rewrite is 99% done.
